mito_test_python_testcase(tests/mito.ext/integrate_2D.py)
mito_test_python_testcase(tests/mito.ext/scalar_function_2D.py)
mito_test_python_testcase(tests/mito.ext/scalar_function_3D.py)
mito_test_python_testcase(tests/mito.ext/vector_2D.py)
mito_test_python_testcase(tests/mito.ext/vector_3D.py)