mito_test_driver(tests/mito.lib/divergence-theorem/main.cc)
mito_test_driver(tests/mito.lib/erase-element/main.cc)
mito_test_driver(tests/mito.lib/fields/main.cc)
mito_test_driver(tests/mito.lib/flip-diagonal/main.cc)
mito_test_driver(tests/mito.lib/functions/main.cc)
mito_test_driver(tests/mito.lib/gent/main.cc)
mito_test_driver(tests/mito.lib/geometry/cell_barycenter.cc)
mito_test_driver(tests/mito.lib/io/load-summit-mesh-2D.cc)
mito_test_driver(tests/mito.lib/io/load-summit-mesh-3D.cc)
mito_test_driver(tests/mito.lib/io/load-summit-segment-mesh-3D.cc)

if(WITH_VTK)
    mito_test_driver_pytest_check(tests/mito.lib/io/write-point-cloud-to-vtk.cc)
    mito_test_driver_pytest_check(tests/mito.lib/io/write-summit-mesh-3D-to-vtk.cc)
    mito_test_driver_pytest_check(tests/mito.lib/io/write-summit-mesh-2D-to-vtk.cc)
    mito_test_driver_pytest_check(tests/mito.lib/io/write-tetra-mesh-to-vtk.cc)
endif()

mito_test_driver(tests/mito.lib/mesh/main.cc)

if(WITH_METIS)
    mito_test_driver(tests/mito.lib/mesh/metis_partitioner.cc)
    mito_test_driver(tests/mito.lib/mesh/metis_partitioner_load_mesh.cc)
    if(WITH_MPI)
        mito_test_driver_mpi(tests/mito.lib/mesh/metis_partitioner_mpi.cc 2)
        mito_test_driver_mpi(tests/mito.lib/mesh/metis_partitioner_mpi_load_mesh.cc 2)
    endif()
endif()

mito_test_driver(tests/mito.lib/oriented-simplex/main.cc)
mito_test_driver(tests/mito.lib/point/main.cc)
mito_test_driver(tests/mito.lib/pyre-grids/main.cc)
mito_test_driver(tests/mito.lib/quadrature/main.cc)
if(${WITH_METIS} AND ${WITH_MPI})
    mito_test_driver_mpi(tests/mito.lib/quadrature/main_mpi.cc 2)
endif()
mito_test_driver(tests/mito.lib/segmented-container/main.cc)
mito_test_driver(tests/mito.lib/segmented-container-iterator/main.cc)
mito_test_driver(tests/mito.lib/shared-pointer/main.cc)
mito_test_driver(tests/mito.lib/simplices/main.cc)
mito_test_driver(tests/mito.lib/traits/main.cc)
