mito_test_python_testcase(tests/mito.ext/integrate.py)
mito_test_python_testcase(tests/mito.ext/scalar-field-2D.py)
mito_test_python_testcase(tests/mito.ext/scalar-field-3D.py)
mito_test_python_testcase(tests/mito.ext/vector2D.py)
mito_test_python_testcase(tests/mito.ext/vector3D.py)
