# -*- yaml -*-
#
# Copyright (c) 2020-2024, the MiTo Authors, all rights reserved
#

name: cmake-ubuntu
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:


jobs:
  # build and test the ref that launched this action
  build:
    name: >-
      ${{matrix.target}}
      python-${{matrix.python}}+${{matrix.suite}}-${{matrix.suiteVersion}}
      on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        target: [Debug, Release]
        python: ["3.12"]
        suite: [gcc]
        suiteVersion: ["12"]
        include:
          - suite: gcc
            cc: gcc
            cxx: g++

    steps:
      - name: ${{matrix.os}} refresh
        run: |
          echo " -- update the package cache"
          sudo apt update
          echo " -- upgradables"
          sudo apt list --upgradable
          echo " -- upgrade"
          sudo apt dist-upgrade
          echo " -- install our dependencies"
          sudo apt install -y make cmake libgtest-dev libbenchmark-dev libvtk9-dev libopenmpi-dev libmetis-dev valgrind petsc-dev

      - name: python ${{matrix.python}} setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install distro 'numpy<2.0' pybind11 pytest vtk

      - name: checkout pyre
        uses: actions/checkout@v3
        with:
          repository: pyre/pyre
          fetch-depth: 0
          path: ${{github.workspace}}/pyre
          ref: main

      - name: retrieve pyre commit SHA
        id: pyre-sha
        run: |
          echo "PYRE-SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        working-directory: ${{github.workspace}}/pyre

      - name: cache pyre
        id: cache-pyre
        uses: actions/cache@v3
        with:
          path: ${{runner.temp}}/pyre_install
          key: pyre-${{steps.pyre-sha.outputs.PYRE-SHA}}-${{matrix.os}}+python-${{matrix.python}}+${{matrix.suite}}-${{matrix.suiteVersion}}

      - if: steps.cache-pyre.outputs.cache-hit != 'true'
        name: build pyre
        run: |
          echo " -- switching to the build directory"
          mkdir build
          cd build
          echo " -- configuring the build"
          cmake -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_BUILD_TYPE=${target} -DCMAKE_C_COMPILER=${cc} -DCMAKE_CXX_COMPILER=${cxx} -DPython_ROOT_DIR=${pythonLocation} -Dpybind11_DIR=${pythonLocation}/lib/python${pythonVersion}/site-packages/pybind11/share/cmake/pybind11 ${{github.workspace}}/pyre
          echo " -- building pyre"
          make -j 2 install
          echo " -- clean up"
          cd ${{runner.temp}}
          rm -r build
        env:
          prefix: ${{runner.temp}}/pyre_install
          target: Release
          cc: ${{matrix.cc}}-${{matrix.suiteVersion}}
          cxx: ${{matrix.cxx}}-${{matrix.suiteVersion}}
          pythonVersion: ${{matrix.python}}
        working-directory: ${{runner.temp}}

      - name: list system packages
        run: |
          dpkg -l

      - name: versions
        run: |
          echo " -- platform tag from python"
          python${pythonVersion} -c "import sys; print(sys.platform)"
          echo " -- distribution tag from python"
          python${pythonVersion} -c "import distro; print(distro.id(), distro.version())"
          echo " -- make"
          make --version
          echo " -- cmake"
          cmake --version
          echo " -- python"
          python3 --version
          echo " -- ${{matrix.suite}}"
          ${{matrix.suite}}-${{matrix.suiteVersion}} --version
        env:
          pythonVersion: ${{matrix.python}}

      - name: external dependencies
        run: |
          echo " -- gtest"
          sudo dpkg-query -L libgtest-dev
          echo " -- google-benchmark"
          sudo dpkg-query -L libbenchmark-dev
          echo " -- vtk"
          sudo dpkg-query -L libvtk9-dev
          echo " -- openmpi"
          sudo dpkg-query -L libopenmpi-dev
          echo " -- metis"
          sudo dpkg-query -L libmetis-dev
          echo " -- petsc"
          sudo dpkg-query -L petsc-dev

      - name: locations of python packages
        run: |
          echo " -- distro"
          pip3 show distro
          echo " -- numpy"
          pip3 show numpy
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/numpy/core/include
          echo " -- pybind11"
          pip3 show pybind11
          echo " -- its headers"
          find ${pythonLocation}/lib/python${pythonVersion}/site-packages/pybind11
          echo " -- pytest"
          pip3 show pytest
          echo " -- vtk"
          pip3 show vtk
        env:
          pythonVersion: ${{matrix.python}}

      - name: checkout mito
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          path: mito

      - name: build mito
        run: |
          echo " -- switching to the build directory"
          mkdir build
          cd build
          echo " -- configuring the build"
          cmake -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_BUILD_TYPE=${target} -DCMAKE_CXX_COMPILER=${cxx} -DPython_ROOT_DIR=${pythonLocation} -Dpybind11_DIR=${pythonLocation}/lib/python${pythonVersion}/site-packages/pybind11/share/cmake/pybind11 -DMITO_BUILD_TESTING=ON -DMITO_BUILD_BENCHMARKS=ON -Dpyre_DIR=${{runner.temp}}/pyre_install/share/cmake/pyre -DWITH_VTK=ON  -DWITH_METIS=ON -DWITH_PETSC=ON ${{github.workspace}}/mito
          echo " -- building mito"
          make -j 2 install
        env:
          prefix: ${{runner.temp}}/mito_install
          target: ${{matrix.target}}
          cc: ${{matrix.cc}}-${{matrix.suiteVersion}}
          cxx: ${{matrix.cxx}}-${{matrix.suiteVersion}}
          pythonVersion: ${{matrix.python}}
        working-directory: ${{runner.temp}}

      - name: test mito
        run: |
          echo " -- testing mito"
          ctest --output-on-failure -E postgres.ext
        working-directory: ${{runner.temp}}/build

      - name: check mito app template
        run: |
          echo " -- switching to the build directory"
          mkdir build_app
          cd build_app
          echo " -- configuring the build"
          cmake -DCMAKE_MODULE_PATH="${{github.workspace}}/mito/.cmake" -DCMAKE_BUILD_TYPE=${target} -DCMAKE_CXX_COMPILER=${cxx} -Dmito_DIR=${{runner.temp}}/mito_install/share/cmake/mito -Dpyre_DIR=${{runner.temp}}/pyre_install/share/cmake/pyre ${{github.workspace}}/mito/apps/template
          echo " -- building mito template app"
          make
          echo " -- running mito template app"
          ./main
        env:
          target: ${{matrix.target}}
          cxx: ${{matrix.cxx}}-${{matrix.suiteVersion}}
        working-directory: ${{runner.temp}}

      - name: run valgrind
        run: |
          echo " -- run valgrind on benchmark test"
          valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --xml=yes --xml-file=memcheck.xml --leak-resolution=high --show-reachable=yes --num-callers=20 --track-fds=yes --track-origins=yes --gen-suppressions=all --suppressions=${{github.workspace}}/mito/.valgrind.supp --log-file='valgrind.txt' -v ./benchmarks/benchmarks.mito.lib.integration.integration
          echo " -- check valgrind output"
          python3 ${{github.workspace}}/mito/scripts/check_valgrind.py
        working-directory: ${{runner.temp}}/build

      - name: create artifact
        if: ${{!cancelled()}}
        uses: actions/upload-artifact@v4
        with:
          name: mito_build_${{matrix.target}}
          path: ${{runner.temp}}/build
          retention-days: 7

# end of file
